# Generated by Django 4.2.4 on 2023-10-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao_data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Aprovada', 'Aprovada'), ('Faturada', 'Faturada'), ('Auditada', 'Auditada'), ('Cancelada', 'Cancelada')], default='Aguardando', max_length=20)),
                ('especialidade', models.CharField(max_length=100)),
                ('credenciado', models.CharField(max_length=100)),
                ('verificador', models.CharField(default='000000', max_length=6)),
                ('coparticipacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aprovacao_data', models.DateTimeField(blank=True, null=True)),
                ('faturamento_data', models.DateTimeField(blank=True, null=True)),
                ('auditoria_data', models.DateTimeField(blank=True, null=True)),
                ('cancelamento_data', models.DateTimeField(blank=True, null=True)),
                ('aprovacao_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovador', to=settings.AUTH_USER_MODEL)),
                ('auditoria_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditor', to=settings.AUTH_USER_MODEL)),
                ('cancelamento_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelador', to=settings.AUTH_USER_MODEL)),
                ('criacao_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criador', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('faturamento_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
